name: Docker Image
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: >-
          docker build . --file Dockerfile --tag ${{ github.repository }}${{
          github.event.pull_request.head.repo.full_name }}:v2
      - name: Tag the Docker image
        run: >-
          docker tag nesrine-snoussi/automating-containerization-api:v2 ${{
          secrets.DOCKERHUB_USERNAME }}/automating-containerization-api:v2
      - name: Push the Docker image to Docker Hub
        run: >-
          docker push ${{ secrets.DOCKERHUB_USERNAME
          }}/automating-containerization-api:v2
